/**
 * Regenerates CATALOG.md from the catalog itself.
 * A hand-written model table drifts the day someone adds a model.
 *
 *   bun run --cwd packages/ai docs:catalog
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { getModels, getProviders } from "../src/catalog";
import type { AIModelConfig } from "../src/constants/model.types";

function family(model: AIModelConfig): string {
	return model.id.includes("/") ? model.id.split("/")[0] : model.id;
}

function servedBy(model: AIModelConfig): string {
	return model.provider ?? "—";
}

function list(values: string[] | number[] | undefined): string {
	return values?.length ? values.join(", ") : "—";
}

function durations(model: AIModelConfig): string {
	if (model.durationOptions?.length)
		return `${model.durationOptions.join(", ")}s`;
	if (model.minDuration || model.maxDuration) {
		return `${model.minDuration ?? "?"}–${model.maxDuration ?? "?"}s`;
	}
	return "—";
}

function capabilities(model: AIModelConfig): string {
	const caps = model.videoCapabilities;
	if (!caps) return "—";
	const flags: string[] = [];
	if (caps.startFrame) flags.push("start frame");
	if (caps.endFrame) flags.push("end frame");
	if (caps.characterRef) flags.push("character ref");
	if (caps.motionControl) flags.push("motion control");
	if (caps.refVideo || caps.referenceVideo) flags.push("ref video");
	if (caps.audioToggle) flags.push("audio toggle");
	if (caps.elements) flags.push(`elements (max ${caps.elements.max})`);
	if (caps.multishot && caps.multishot.mode !== "off") flags.push("multishot");
	return flags.length ? flags.join(", ") : "—";
}

function section(
	title: string,
	models: AIModelConfig[],
	video: boolean,
): string {
	const rows: string[] = [];
	const families = [...new Set(models.map(family))].sort();

	for (const name of families) {
		const group = models.filter((model) => family(model) === name);
		rows.push(`\n### ${name}\n`);
		rows.push(
			video
				? "| id | duration | resolutions | aspect | capabilities | served by |\n|---|---|---|---|---|---|"
				: "| id | resolutions | aspect | input | served by |\n|---|---|---|---|---|",
		);
		for (const model of group.sort((a, b) => a.id.localeCompare(b.id))) {
			rows.push(
				video
					? `| \`${model.id}\` | ${durations(model)} | ${list(model.supportedResolutions)} | ${list(model.supportedAspectRatios)} | ${capabilities(model)} | ${servedBy(model)} |`
					: `| \`${model.id}\` | ${list(model.supportedResolutions)} | ${list(model.supportedAspectRatios)} | ${model.inputType} | ${servedBy(model)} |`,
			);
		}
	}

	return `## ${title} (${models.length})\n${rows.join("\n")}\n`;
}

const AI_MODELS = getModels();
const video = AI_MODELS.filter((m) => m.category === "video");
const image = AI_MODELS.filter((m) => m.category === "image");
const text = AI_MODELS.filter((m) => m.category === "text");
const audio = AI_MODELS.filter((m) => m.category === "audio");
const native = AI_MODELS.filter((m) => m.provider);

const doc = `<!-- Generated by scripts/generate-catalog-doc.ts. Do not edit by hand. -->
# Supported catalog

${AI_MODELS.length} models: ${video.length} video, ${image.length} image, ${audio.length} speech, ${text.length} text.

Every model is served by its vendor's own API — no aggregator sits in between, so
the key you configure is the account that runs the work and bills it.

Providers: ${getProviders().join(", ")}.

Every model here is reachable through one \`ai.image\`/\`ai.video\` call with the same
params. What differs between them is only what this table records: durations,
resolutions, aspect ratios and capabilities.

${section("Video", video, true)}
${section("Image", image, false)}
${section("Speech", audio, false)}
${section("Text", text, false)}
`;

writeFileSync(join(import.meta.dir, "..", "CATALOG.md"), doc);
console.log(
	`CATALOG.md: ${AI_MODELS.length} models (${native.length} native, ${AI_MODELS.length - native.length} via aggregator)`,
);
